FROM nginx:stable-alpine AS runner

ADD dist /usr/share/nginx/html/
RUN sed -i '9 a try_files $uri $uri/ /index.html;' /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["/bin/sh", "-c", "nginx -g \"daemon off;\""]
